/*This file is generated by Proxy_configure
Header store the flag for Proxy_Client Proxy_Server */

#include <stdio.h> 

#define PROXY_C89  1 
#define PROXY_POSIX 200112L  
#define PROXY_LP64 1
#define PROXY_LINUX 1
#define PROXY_SEND_C 1
typedef unsigned char byte;
